### ISSUE TITLE
106 cant travel upwards or downwards

### ISSUE THREAD

**Issue by Coroneljones** [SS13-SCP13/SS13-SCP13#104]
#### Description of issue

106 is unable to go through the floor or ceiling of the rooms, saying that "ice is blocking you" for ceilings, and "the plating is blocking you" for moving downwards, forcing him to either find a ladder, stairs or use the elevator

#### Difference between expected and actual behavior

Unknown if intended or not, but 106 is able to go through airlocks, so I would assume that grilles, plating or the ceiling wouldnt be too much of an obstacle for travel, instead of forcing 106 to take the Elevator

#### Steps to reproduce 
Be SCP 106
Open IC tab
Click "move upwards/down"
Watch as it says the Ice is in your way

#### Length of time in which bug has been known to occur
Actively on-going

#### Client version, Server revision & Game ID
Client Version: 512
Server Revision: Revision Unknown
Game ID: bVm-cmIh

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by JakeDaBoss** [comment]
This also includes ladders, confirmed after testing.

**Comment by JakeDaBoss** [comment]
Fixed.
