### ISSUE TITLE
Several APCs don't detect external power

### ISSUE THREAD

**Issue by Pandolphina** [SS13-SCP13/SS13-SCP13#106]
#### Description of issue

Certain areas (Engineering lounge area, most of medbay,) report no external power even when it is present

#### Difference between expected and actual behavior

Rooms should show external power and charge. They do not.

#### Steps to reproduce 

Join as engineer 
Set up RUSTs
Check Engineering lounge/medbay APC

#### Client version, Server revision & Game ID
Byond Beta (Latest), server révision present on server during test at time of the creation of this error.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players (I'm the only person to ever play Engineer)
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by JakeDaBoss** [comment]
Should be fixed.
