### ISSUE TITLE
Several Doors are unhackable/Unopenable 

### ISSUE THREAD

**Issue by Pandolphina** [SS13-SCP13/SS13-SCP13#107]
#### Description of issue
Several doors (Site Directors office, SCP 106s containment) are unhackable.

Second, even the CE cannot open the side room of SCP 106s Containment Chamber, making the field generators impossible to set up.

#### Difference between expected and actual behavior
Doors should be hackable, or at least possible to have it be brute forced and welded open if bolted.

Allow CE/Engineers access to field SCP 106s chamber for Field Generator setup

#### Steps to reproduce 
Join as engineer/CE
Attempt to hack/open 106s Containment Chamber or Site Directors office

Join as security 
Shoot at doors until they break
Attempt to crowbar/weld bolts

#### Length of time in which bug has been known to occur

As long as the two tests (yesterday and today at time of creation of issue report) have been active.

#### Client version, Server revision & Game ID
Byond version 512

Server revision: Public test at time of creation of issue

Game ID: Unknown 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by JakeDaBoss** [comment]
Fixed.
