### ISSUE TITLE
Minor CE/Engineer issues

### ISSUE THREAD

**Issue by Pandolphina** [SS13-SCP13/SS13-SCP13#108]
#### Description of issue
CE cannot use all APCs (Nuke, for example)

Engineer cannot unlock ANY APCs

Nuke unlock button does not open the nuke blast door 

#### Difference between expected and actual behavior
CE should have access to all APCs

Engineers should have access to all/at least non critical APCs

#### Steps to reproduce 
Join as CE
Attempt to unlock Nuke APC

Join as engineer 
Attempt to open any APC

Join as CE
Walk into command center
Use nuke unlock button

#### Client version, Server revision & Game ID
Byond Version 512
Server version: Current version at time of public test at time of creation of this issue report
Game ID: Unknown 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by JakeDaBoss** [comment]
Assigned Priority 3: Low, considering we need to check all the APC's in /every/ area now.

**Comment by Pandolphina** [comment]
I'd check it myself, but the Github has a different map file if I'm not mistaken

**Comment by M11gamer** [comment]
uh nop, just open the map right now and the id is the right one.

**Comment by Pandolphina** [comment]
Huh. Maybe something happened that round.

**Comment by JakeDaBoss** [comment]
No, you're actually right. The access requirements were wrong. Fixed now.

**Comment by Pandolphina** [comment]
Thanks.

**Comment by M11gamer** [comment]
strange in my map they are good, I remember testing it a lot too :{

**Comment by JakeDaBoss** [comment]
Please report any repeat incidents of this exact nature.
