### ISSUE TITLE
Lockers remove cone of vision.

### ISSUE THREAD

**Issue by Wulfestwulf** [SS13-SCP13/SS13-SCP13#123]
#### Description of issue
Lockers remove your cone of vision letting you see in all directions.

#### Difference between expected and actual behavior
Expected to have same cone of view when you enter.

#### Steps to reproduce 
Take a locker into a big room, open it and hide inside of it.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by JakeDaBoss** [comment]
Right, well, technically you're not meant to be looking out of it, or specifically only one direction. You can't look through the side of it, can you?
