### ISSUE TITLE
Copied paper uses the wrong sprite

### ISSUE THREAD

**Issue by Chopchop1614** [SS13-SCP13/SS13-SCP13#125]
#### Description of issue
When paper which has been written on is copied the copied paper uses the sprite of blank paper despite having writing on it.

#### Difference between expected and actual behavior
I expected the sprite of written paper on the copied paper.

#### Steps to reproduce 
Write on paper, copy paper.

#### Specific information for locating

photocopier in Bullpen Office

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: Revision Unknown
Game ID: bVr-ddca

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by JakeDaBoss** [comment]
So the sprite has that of an empty paper, am I correct in this?

**Comment by Chopchop1614** [comment]
Yup.
