### ISSUE TITLE
049-1 cured by SCP-500 do not return to the race they once were.

### ISSUE THREAD

**Issue by Affurit** [SS13-SCP13/SS13-SCP13#177]
#### Description of issue

This may not be a wide issue in the future due to the fact we only really have humans on board, but due to the fact that we're using SCPs for species this may end up being a bit weird in some regards.

#### Difference between expected and actual behavior

The subject should potentially return to it's past species.

#### Steps to reproduce 

Kill someone as 049, zombie them, feed 500.

#### Length of time in which bug has been known to occur

Since creation.

#### Client version, Server revision & Game ID

Reeee.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by kachnov** [comment]
fixed
