### ISSUE TITLE
294 HyperSpecific Requests

### ISSUE THREAD

**Issue by Affurit** [SS13-SCP13/SS13-SCP13#179]
#### Description of issue

294 requires entries to be 1 word. E.G Orangejuice. This isn't a bug but if it could be changed it'd be nice. I'd understand if it's not worth the effort if the fix is difficult. 

#### Difference between expected and actual behavior

I think it'd be nice if it were possible to seperate it, if not, oh well, we can inform people.

#### Steps to reproduce 

Try to create something requiring 2 words.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by MarinaGryphon** [comment]
Looking at the code, I believe that the logic should just be duplicated for the input-- in that case, inputting `orange juice` would result in `orangejuice` being passed, making the logic work. It would also, of course, make `e thanol`, `co ff ee`, etc. work, but maybe 294 can just understand the spirit of the instructions?
