### ISSUE TITLE
Missing wall in Main Control Room.

### ISSUE THREAD

**Issue by Nightspark43** [SS13-SCP13/SS13-SCP13#183]
#### Description of issue
There seems to be a missing wall in the Main Control Room leading to Airless plating and space, likely draining the air from the rest of the area.

#### Specific information for locating
Go to the Main Control Room.
https://gyazo.com/5a24764e805a558d543d632bf83b5a42

#### Client version, Server revision & Game ID
Client Version: 512
Server Revision: Revision Unknown
Game ID: bV1-cSIH
Current map: Foundation Site 53

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by JakeDaBoss** [comment]
Fixed.
