### ISSUE TITLE
Mining Factory conveyer belts dont work.

### ISSUE THREAD

**Issue by Bryssel** [SS13-SCP13/SS13-SCP13#184]
#### Description of issue
Conveyer belts in the mining factory don't work.

#### Difference between expected and actual behavior
As expected, they should work fine but they don't work.

#### Steps to reproduce 
Just flip the switch that should get them rolling. You'll see they don't work.

#### Specific information for locating

Mining Factory, conveyer belts.

#### Length of time in which bug has been known to occur
Ever since DSM90 this has been an issue on the maps.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: Revision Unknown
Game ID: bV1-c1lL
Current map: Foundation Site 53

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by JakeDaBoss** [comment]
Known issue so far. No clue what causes it.

**Comment by JakeDaBoss** [comment]
Code issue.
