### ISSUE TITLE
There no oxygen in the mining area

### ISSUE THREAD

**Issue by IcedPotato** [SS13-SCP13/SS13-SCP13#185]
#### Description of issue

There's no oxygen in the mining area.

#### Difference between expected and actual behavior

There should be oxygen.

#### Steps to reproduce 

Open the door and step outside.

#### Specific information for locating

Mining area.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by JakeDaBoss** [comment]
This is simply to do with the cave system not spawning air. I'll possibly have a way of fixing this.
