### ISSUE TITLE
Class D kitchen is lacking several utensils.

### ISSUE THREAD

**Issue by IcedPotato** [SS13-SCP13/SS13-SCP13#186]
#### Description of issue

The kitchen is lacking several utensils such as beakers and a stove from what has been said by another player.

#### Difference between expected and actual behavior

Cannot cook food besides using the microwave.

#### Specific information for locating

Class D kitchen.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by JakeDaBoss** [comment]
Stove isn't an item. The rest is fixed.
