### ISSUE TITLE
Virology and Medical Admission decals are overlapping

### ISSUE THREAD

**Issue by Bryssel** [SS13-SCP13/SS13-SCP13#188]
#### Description of issue
There are decals that have duplicated ontop of the original in Medical.

#### Difference between expected and actual behavior
There should only be one sprite, not 2 overlapping one another.

#### Steps to reproduce 
Head over to medical and you'll see multiple of these decals in an L form.

#### Specific information for locating

Virology and Medical Admission have these.

#### Length of time in which bug has been known to occur
This has only occurred on Site 53.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: Revision Unknown
Game ID: bV1-dbYE
Current map: Foundation Site 53

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by JakeDaBoss** [comment]
Known issue, will be looked into.
