### ISSUE TITLE
SCP-513 is not blockable by earmuffs.

### ISSUE THREAD

**Issue by Bryssel** [SS13-SCP13/SS13-SCP13#191]
#### Description of issue
Wearing earmuffs does not negate SCP-513's effect.

#### Difference between expected and actual behavior
Since earmuffs block sound, it should ignore any sound SCP-513 makes.

#### Steps to reproduce 

Wear earmuffs and ring the bell.

#### Specific information for locating

SCP-513 Chamber

#### Length of time in which bug has been known to occur
This has only occurred on Site 53.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: Revision Unknown
Game ID: bV1-dbYE
Current map: Foundation Site 53

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by JakeDaBoss** [comment]
Fixed in #194
