### ISSUE TITLE
CE can't use Command and Comms program or Send Faxes

### ISSUE THREAD

**Issue by Pandolphina** [SS13-SCP13/SS13-SCP13#203]
#### Description of issue
Can't open Command and Communications program as CE, and can't send faxes

#### Difference between expected and actual behavior
Should be able to open program and send faxes, can't.

#### Steps to reproduce 
1. Go to computer as CE
2. Attempt to open program
3. Fail

1. Go to fax machine as CE
2. Load paper
3. Attempt to swipe ID
4. Fail

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by JakeDaBoss** [comment]
All of this works fine for me. Issue closed for the moment being. If it happens again, re-open the issue with more details.
