### ISSUE TITLE
Missing items in the janitorial room.

### ISSUE THREAD

**Issue by LucasOCastro** [SS13-SCP13/SS13-SCP13#204]
#### Description of issue

The janitorial room needs more items.

#### Difference between expected and actual behavior

I expected the janitorial room to have trash bags for the carts, buckets to fill in the carts and trash bins to put the collected trash in, but all that is there are light bulbs, space cleaners, carts and mops. Would also be good to have a way to refill space cleaners.

#### Specific information for locating

The janitorial closet, north of Class-D area.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by JakeDaBoss** [comment]
Was there nothing in the lockers?

**Comment by LucasOCastro** [comment]
Only light bulb boxes and one bottle of space cleaner per locker.
