### ISSUE TITLE
Mis-numbered and mis-cataloged SCP reports in the archive

### ISSUE THREAD

**Issue by Stitcher-Geralf** [SS13-SCP13/SS13-SCP13#205]
#### Description of issue
There are 2 documents, called SCP-049 (There's actually two SCP-049 documents) and SCP-513, that describe SCP's other than the ones they are named after.

#### Difference between expected and actual behavior
Instead of finding info on SCP 513, I got a copy of SCP 500's report. Then I checked the whole archive and found that there are two SCP 049 papers, with one describing SCP 012.

#### Steps to reproduce 
Has happened two rounds in a row

#### Length of time in which bug has been known to occur

I'm guessing since the papers were put into the archive

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Stitcher-Geralf** [comment]
Clicked close issue button on accident.

**Comment by JakeDaBoss** [comment]
Holy shit. Thanks! These things are incredibly easy to look over if you have to work with them a lot.
