### ISSUE TITLE
Science stairs don't look like they exist

### ISSUE THREAD

**Issue by Stitcher-Geralf** [SS13-SCP13/SS13-SCP13#212]
#### Description of issue
Stairs down to Science don't look like they exist.

#### Difference between expected and actual behavior
Didn't even know that Science was there.

#### Steps to reproduce 
Is constant.

#### Specific information for locating

![image](https://user-images.githubusercontent.com/42708720/44930025-a0055f00-ad22-11e8-8ffc-0c2b90b00673.png)

#### Length of time in which bug has been known to occur

When the sever launched on 8/31/18

#### Client version, Server revision & Game ID

Whatever it was then

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by ComradeCorbyn** [comment]
This happens to me for some stairs, but entering and leaving the area fixes it occasionally.

**Comment by JakeDaBoss** [comment]
We can't currently replicate this issue. @kachnov will keep an eye out for when it happens and we'll go from there.

**Comment by JakeDaBoss** [comment]
Current fix:
As @ComradeCorbyn mentioned, exit and enter the area again, a few times possibly. That should fix it.
