### ISSUE TITLE
Issues when using the "Become Class-D" command

### ISSUE THREAD

**Issue by IcedPotato** [SS13-SCP13/SS13-SCP13#216]
#### Description of issue

Issue #1: You aren't subject to gravity when spawning, until you walk to another zone. I.e, the assignment area.

Issue #2: You always spawn as a baldie.

#### Difference between expected and actual behavior

There should be gravity and you should be able to choose which character you want to spawn as.

#### Steps to reproduce 

Ghost, use "Become Class-D" in ghost tab. Go south to see the issue with gravity.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: 8e3288a692d078fd2d0a01f9e7d6da4e34ea985a - experimental - 2018-08-26
Game ID: bV8-cVeI
Current map: Foundation Site 53

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Affurit** [comment]
How on earth does that even happen...?
