### ISSUE TITLE
Xenobiology and Xenobotany impossible to do.

### ISSUE THREAD

**Issue by Pandolphina** [SS13-SCP13/SS13-SCP13#219]
#### Description of issue
Xenobiology lacks syringes, a chem grinder and a phoron sheet, making it impossible to use most reactions.

Xenobotany lacks all the gene splicing machines.

#### Difference between expected and actual behavior
Machines should be there.

They aren't.

#### Steps to reproduce 
1. Go senior scientist
2. Go into xenobiology
3. See lack of chem grinder, phoron and syringes
4. Cry.

1. Go senior scientist
2. Go into xenobotany
3. See lack of gene splicing machines
4. Realize you're literally as useful as the D Class botany
5. Cry

#### Client version, Server revision & Game ID

L A T E S T

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Bryssel** [comment]
While it would be nice to have syringes at round start, you can quickly make them in the Autolathe.

**Comment by Pandolphina** [comment]
That IS true. My mistake. Point about the grinder still stands.

**Comment by Affurit** [comment]
Why not print off a grinder circuit?

_jk_
