### ISSUE TITLE
Senior Scientist can't use destructive analyzer

### ISSUE THREAD

**Issue by Pandolphina** [SS13-SCP13/SS13-SCP13#220]
#### Description of issue
When attempting to interact with the R&D console Destructive Analyzer program as Senior Scientist, it gives "access denied"

#### Difference between expected and actual behavior
Should allow you to use the program.

Gives you "access denied".

#### Steps to reproduce 
1. Join as senior scientist
2. Go to destructive analyzer console
3. Attempt to use
4. Cry

#### Client version, Server revision & Game ID

Latest

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Bryssel** [comment]
Even RD can't use it. Haven't tested with site director.

**Comment by Pandolphina** [comment]
Y A Y.

**Comment by Affurit** [comment]
May be something to do with ID locking and bay's weirdass system. I know that Persistence actually made this a feature.
