### ISSUE TITLE
Security Insignia Icon Stuck To Hand

### ISSUE THREAD

**Issue by Affurit** [SS13-SCP13/SS13-SCP13#222]
#### Description of issue
This is sad.

#### Difference between expected and actual behavior
It's weird af and the Icon never leaves.

#### Steps to reproduce 
Pick up a security insignia.

Suffer.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Affurit** [comment]
Okay it happens with guard tags too.

**Comment by Affurit** [comment]
Seems to be an issue with accessories.

**Comment by JakeDaBoss** [comment]
I can drop it just fine.

**Comment by JakeDaBoss** [comment]
All of it.

**Comment by Affurit** [comment]
Weird, last round I played, I had like 7 accessories stacked on top of eachother in my hand that wouldn't go away.

**Comment by JakeDaBoss** [comment]
OH. That's an optical glitch. If you can drop them, there's no issue. That happens sometimes due to lag AFAIK, or some other reason. You'd just need to reconnect and they should be gone.

**Comment by Affurit** [comment]
Oooh...

**Comment by JakeDaBoss** [comment]
Still, it's something we should look into.

**Comment by JakeDaBoss** [comment]
Hasn't occurred recently.
