### ISSUE TITLE
Male character can only wear Female underwear.

### ISSUE THREAD

**Issue by GreenTea988** [SS13-SCP13/SS13-SCP13#225]
#### Description of issue
My male character can only wear Female underwear.

#### Difference between expected and actual behavior
I normally expect a guy to wear guys underwear and vice versa?

#### Steps to reproduce 
Opening the character setup menu. 

#### Specific information for locating
None exactly.

#### Length of time in which bug has been known to occur
It's been happening since I joined the server, which was yesterday as of making this post.

#### Client version, Server revision & Game ID
Server Revision: 8e3288a692d078fd2d0a01f9e7d6da4e34ea985a - experimental - 2018-08-26

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Affurit** [comment]
Maybe your character is just into that? 

Are you sure it’s a Male???????

**Comment by GreenTea988** [comment]
pfft.
Yeah, it's Male, my examine verbs and stuff say He, too.

**Comment by Affurit** [comment]
When was the last time you checked?

Touched the jasper stone recently?

More seriously, have you tried changing sex back and forth?

**Comment by GreenTea988** [comment]
Haven't touched the stone, and I changed my sex to male because the starter one I got was Female.
The last time I checked was uhh, the round I was playing. 
(Which is why it took so long to respond)

**Comment by Affurit** [comment]
*Shrug* 

It's not hurting anyone, is it?

Gives you something fun to discuss if your clothes ever fall off.

I'll look into it, not sure what I'll find, best advice is to just swap from male to female and back again until it fixes or something.

**Comment by GreenTea988** [comment]
pfft.
Can do, hue

**Comment by JakeDaBoss** [comment]
DID THIS BECOME A FORUM, CAN I JOIN IN ON THE MYSOGINY.

**Comment by JakeDaBoss** [comment]
For real, we'll look into this at some point, but it's not a top priority.

**Comment by Affurit** [comment]
I imagine it's a bottom's priority tho...

**Comment by MrBobCool** [comment]
I think it's pretty fucking hot.


_I'm kidding god no._

**Comment by Affurit** [comment]
Oh Woh

**Comment by buffyuwu** [comment]
https://puu.sh/Bv2Di/3d6a2ca45f.png

????????????

**Comment by Affurit** [comment]
This is a feature not a bug.

/dab

**Comment by kachnov** [comment]
Closed because apparently this is a feature
