### ISSUE TITLE
Multiple Monkey Creation from Fire Extinguisher.

### ISSUE THREAD

**Issue by Titanslayer71** [SS13-SCP13/SS13-SCP13#231]
#### Description of issue

  Gameplay

#### Difference between expected and actual behavior

  The production of 2 additional monkeys.

#### Steps to reproduce 

1. Put a monkey cube down.
2. Use a Fire Extinguisher and spray on the monkey cube. 

#### Specific information for locating

  N/A

#### Length of time in which bug has been known to occur

  Unknown

#### Client version, Server revision & Game ID

SCP 13 Test (9/1/18)
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this]( https://github.com/SS13-SCP13/SS13-SCP13/issues )
![monkey](https://user-images.githubusercontent.com/42903681/44952390-ff529480-ae32-11e8-8e76-df40c67677ce.png)

**Comment by JakeDaBoss** [comment]
Updated to high priority, since it spammed and crashed the server.
