### ISSUE TITLE
Miners need a bag of some sort.

### ISSUE THREAD

**Issue by LucasOCastro** [SS13-SCP13/SS13-SCP13#233]
#### Description of issue

Miners need a backpack/satchel to carry their tools around.

#### Difference between expected and actual behavior

There are too much mining tools, and going back to get them when needed is not productive.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: 8e3288a692d078fd2d0a01f9e7d6da4e34ea985a - experimental - 2018-08-26
Game ID: bV0-cefN

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this]( https://github.com/SS13-SCP13/SS13-SCP13/issues )

**Comment by Pandolphina** [comment]
What tools? Pickaxe on back slot, mesons on face, ore bag on belt.
