### ISSUE TITLE
The buttons in SCP-513's chamber do not work.

### ISSUE THREAD

**Issue by LucasOCastro** [SS13-SCP13/SS13-SCP13#234]
#### Description of issue

Guards have to actually enter 513's containment to open its box.

#### Difference between expected and actual behavior

The buttons in the observation/control room at 513's chamber are not working, so a guard needs to enter the room with the bell to open the box.

#### Steps to reproduce 

Try to press the buttons next to 513's chamber.

#### Length of time in which bug has been known to occur

Whenever someone tries to test 513.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: 8e3288a - experimental - 2018-08-26
Game ID: bV0-cefN

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this]( https://github.com/SS13-SCP13/SS13-SCP13/issues )

**Comment by steamp0rt** [comment]
Possibly a mapping issue

**Comment by ghost** [comment]
Possibly a mapping issue @JakeDaBoss

**Comment by JakeDaBoss** [comment]
Issue closed. Can't be fixed currently, as it appears windoors don't operate the way airlocks do.
