### ISSUE TITLE
Maybe 173 shouldn't teleport.

### ISSUE THREAD

**Issue by Affurit** [SS13-SCP13/SS13-SCP13#236]
#### Description of issue
173 seems to be able to break LoS by teleporting behind people, thus allowing it to go on a murder spree by narrowly escaping vision cones. Making it just move to the target instead would make a little bit better.

#### Difference between expected and actual behavior
We kind of expected it to happen, it's intended, as per the code.

#### Steps to reproduce 
Watch 173 teleport behind someone.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this]( https://github.com/SS13-SCP13/SS13-SCP13/issues )

**Comment by ghost** [comment]
there's like, a 5 second delay between each necksnap, tho.
