### ISSUE TITLE
For some reason the garbage collector is hogging up a huge amount of resources

### ISSUE THREAD

**Issue by ma44** [SS13-SCP13/SS13-SCP13#240]
#### Description of issue
The garbage collector contributes a huge amount of lag to a private server I was hosting, this was taken about 9 minutes in but probably happens before that
https://gyazo.com/7e7964078ecfd02902239dd9c29bed96

#### Difference between expected and actual behavior
Expected: Garbage collector to properly delete things and not get stuck
Actual: Garbage collector hangs up

#### Steps to reproduce 
Run the game

#### Specific information for locating

Master controller to see garbage collector have a massive ms, profiler sorted by CPU time

#### Length of time in which bug has been known to occur

Seems to be from beginning of game

#### Client version, Server revision & Game ID

As of 7:18 PM CST today

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this]( https://github.com/SS13-SCP13/SS13-SCP13/issues )

**Comment by kachnov** [comment]
Fixed
