### ISSUE TITLE
.rsc, .int and .lk project files are included in repo. 

### ISSUE THREAD

**Issue by PJB3005** [SS13-SCP13/SS13-SCP13#25]
e17ec759ecc041aea14cf5ff516445d734e28447 removed the git ignore rule for these files and they're now committed into the repo, bloating it a ton.

**Comment by PJB3005** [comment]
You still need to delete the files themselves.

**Comment by outbools** [comment]
it keeps happening
Delete it again and force everyone to checkout to new version

**Comment by PJB3005** [comment]
And you just messed it up again with 83828dec6346779623076acadaddde9721c47419.

**Comment by JakeDaBoss** [comment]
Just did. Thanks.
