### ISSUE TITLE
Denied Access to the Air Alarms as any of the Engineering Staff

### ISSUE THREAD

**Issue by Ryboflave** [SS13-SCP13/SS13-SCP13#251]
#### Description of issue
While playing as a Chief Engineer, Senior Engineer, Engineer, and Junior Engineer, I was unable to access the Air Alarms on the station. (As a side note: They can be accessed by any of the engineers via a computer with the Atmospheric Control program)

#### Difference between expected and actual behavior
Expected:
Chief Engineer - Access to the Air Alarms.
Senior Engineer - Access to the Air Alarms.
Engineer - Access to the Air Alarms.
Junior Engineer - Access to Air Alarms.

Actual:
Chief Engineer - Access Denied to the Air Alarms.
Senior Engineer - Access Denied to the Air Alarms.
Engineer - Access Denied to the Air Alarms.
Junior Engineer - Access Denied to Air Alarms.

#### Steps to reproduce 
Join Round as Chief Engineer, Senior Engineer, Engineer, or Junior Engineer
Go to an Air Alarm
Unlock the Air Alarm with your ID
Access is denied appears in chat box

#### Length of time in which bug has been known to occur

At least since September 4th, 2018 to Present. (I only just started playing)

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: fd509dadc877ad26ba35be00db0148dff867e5c0 - experimental - 2018-09-06

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this]( https://github.com/SS13-SCP13/SS13-SCP13/issues )

**Comment by Affurit** [comment]
Should anyone have access?

**Comment by Pandolphina** [comment]
I'd imagine at least the CE would have an "override" access for most/all devices

**Comment by Affurit** [comment]
The only thing is that we don’t have much need for it other than to troll tbh

**Comment by Pandolphina** [comment]
Stopping trollling and area denial in CI raids and maybe if we add human SCPs?

**Comment by Affurit** [comment]
No one can troll if no one has access. Area denial will undoubtably fuck up everyone’s shit.

We kinda have human SCPs and no reason to use atmos yet

**Comment by Pandolphina** [comment]
I mean trolling is as easy to setting the output pump to max and over pressurizing everyone but I see your point. Keep them locked.
