### ISSUE TITLE
Vision Cones do not make items disappear.

### ISSUE THREAD

**Issue by JakeDaBoss** [SS13-SCP13/SS13-SCP13#26]
#### Description of issue
Vision Cones do not make items behind a player disappear.

#### Difference between expected and actual behavior
I reckon that the items that are to the back of someone should not appear. Unless this is part of the memorising part?

#### Steps to reproduce 
Spawn items, turn back to.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by mattroks101** [comment]
This isn't a glitch this is intentional. Items disappearing causes severe lag. And it's incredibly clunky to play with.

**Comment by EndlessEllipse** [comment]
This isn't a glitch, this is intended

**Comment by JakeDaBoss** [comment]
Noted.
