### ISSUE TITLE
Computer programs have no var for one_access

### ISSUE THREAD

**Issue by JakeDaBoss** [SS13-SCP13/SS13-SCP13#288]
#### Description of issue
The computer, tablet and laptop programs have no one_access_req var like doors have. This impedes the ability to make programs available on a wider scale where such is reasonable.

#### Difference between expected and actual behavior
Should have one_req access.

#### Specific information for locating

code\modules\modular_computers\file_system\programs\command\comm.dm:14:error: req_one_access: undefined var (example), all programs require this.

**Comment by kachnov** [comment]
fixed
