### ISSUE TITLE
SCP-049-1 is sometimes unable to smash doors

### ISSUE THREAD

**Issue by Harcourt1** [SS13-SCP13/SS13-SCP13#289]
this is due to the fact that when the panel breaks open the scp is unable to continue breaking the door down becuase the panel opens. 

My suggested solution is just not having the panel open for the SCP and not allowing it to interact with the panel.

**Comment by JakeDaBoss** [comment]
Not an issue.

This is due to the door bolts dropping. I'm fairly sure this has to do with a failsafe mechanic embedded in the high security airlocks.
