### ISSUE TITLE
Fabrication takes a SUPER long time.

### ISSUE THREAD

**Issue by Pandolphina** [SS13-SCP13/SS13-SCP13#296]
#### Description of issue
Exosuit fabricator/protolathe takes INCREDIBLY long to print something.

#### Difference between expected and actual behavior
Odysseus Chassis should take 10 seconds to make, takes around a minute

Protolathe items should take around 20 seconds to make, take 2 minutes.

#### Steps to reproduce 
1. Print literally anything.
2.Cry

#### Client version, Server revision & Game ID

Latest

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this]( https://github.com/SS13-SCP13/SS13-SCP13/issues )

**Comment by Affurit** [comment]
Mayhaps you should just get good.

**Comment by Pandolphina** [comment]
No u.

But this is an actual issue.

**Comment by kachnov** [comment]
fixed by #298
