### ISSUE TITLE
archivist cant access archives

### ISSUE THREAD

**Issue by braincrab** [SS13-SCP13/SS13-SCP13#305]
#### Description of issue
the archivist cannot enter the Keter and restricted archives as the doors do not open

#### Difference between expected and actual behavior
you'd think that a guy whose whole job is based around picking up papers, opening an archive, and shoving them in some folders would, you know, be able to open the damn things. well he cant, doors dont open, you dont have access to them on your card.

#### Steps to reproduce 
1- play as the archivist
2- walk to the archive
3- try to open the archive
4- watch as the door does not open and your job becomes useless
5- find solace in the fact that you can at least open the safe archive, but not any others

#### Specific information for locating

just find the archive, nothing more is really needed

#### Length of time in which bug has been known to occur

no idea, likely since the job was put in as it seems to be an oversight

#### Client version, Server revision & Game ID

client version: 512
server revision: 8e3288a692d078fd2d0a01f9e7d6da4e34ea985a - experimental - 2018-08-26
game id: bWp-dkTF

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this]( https://github.com/SS13-SCP13/SS13-SCP13/issues )

**Comment by JakeDaBoss** [comment]
This isn't a bug, it's a feature. You need the RD to open it for you in order to file certain things.

**Comment by JakeDaBoss** [comment]
Access will be reworked however, so should be able to in the future.
