### ISSUE TITLE
Xenobiologist can't xenobiology.

### ISSUE THREAD

**Issue by PrimusOmega** [SS13-SCP13/SS13-SCP13#306]
#### Description of issue
The xenobiology lab seems to be missing some vital equipment.  Namely the slime extractor and extract fridge.

#### Difference between expected and actual behavior
I expected to actually be able to do xenobiology.

#### Steps to reproduce 
Walk into xenobiology.

#### Specific information for locating
Extract Fridge, Slime Processor

#### Length of time in which bug has been known to occur
The entirety of a round.

#### Client version, Server revision & Game ID
Client Version: 512
Server Revision: 8e3288a692d078fd2d0a01f9e7d6da4e34ea985a - experimental - 2018-08-26
Game ID: bWp-dBRa
Current map: Foundation Site 53

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.
- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this]( https://github.com/SS13-SCP13/SS13-SCP13/issues )

**Comment by MarinaGryphon** [comment]
We don't have slime extractors, but the extract fridge is in the code. I see no reason why it can't be mapped in.
