### ISSUE TITLE
Rollerbeds don't work

### ISSUE THREAD

**Issue by El-Fishii** [SS13-SCP13/SS13-SCP13#307]
#### Description of issue

Rollerbeds, while buckling the patient down, won't move patients. While you drag the bed away,they stay floating mid air where you originally buckled them.

#### Difference between expected and actual behavior

I need to safely move them around instead of opening wounds

#### Steps to reproduce 

Try to buckle someone to a bed and drag them

#### Specific information for locating

As above

#### Length of time in which bug has been known to occur

Happened Sep, 18 at 9pm CST

#### Client version, Server revision & Game ID

Client: 152
Server Revision:  8e3288a692d078fd2d0a01f9e7d6da4e34ea985a - experimental - 2018-08-26
Game ID: bWq-amAu
Happened in previous game to this,don't have it's ID

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x ] Issue could be reproduced at least once
- [x ] Issue could be reproduced by different players
- [x ] Issue could be reproduced in multiple rounds
- [x ] Issue happened in a recent (less than 7 days ago) round
- [x ] [Couldn't find an existing issue about this]( https://github.com/SS13-SCP13/SS13-SCP13/issues )

**Comment by kachnov** [comment]
fixed
