### ISSUE TITLE
Devsay not functional

### ISSUE THREAD

**Issue by JakeDaBoss** [SS13-SCP13/SS13-SCP13#309]
#### Description of issue
Admins can use devsay but devs with +DEBUG can't.

#### Difference between expected and actual behavior
Devs should be able to use Devsay. If a different permission flag is needed, let me know.

#### Steps to reproduce 
Run server on most recent experimental branch.
Assign yourself only +DEBUG
Try to use devsay.

**Comment by kachnov** [comment]
fixed
