### ISSUE TITLE
D-wing medical post could use some extra equipment.

### ISSUE THREAD

**Issue by El-Fishii** [SS13-SCP13/SS13-SCP13#312]
#### Description of issue

First. Could surgical and that medical room be swapped? Having a 1 tile hallway leading to medical equipment which is also the surgery area leads to problems.
Secondly. Could anyone IV drip of two, along with blood bags be set down in the medical post.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this]( https://github.com/SS13-SCP13/SS13-SCP13/issues )

**Comment by NortonDK** [comment]
and some cleaning stuff

**Comment by JakeDaBoss** [comment]
Fixed.
