### ISSUE TITLE
[suggestion] Give 173 the ability to spawn gibs or mucus. 

### ISSUE THREAD

**Issue by Tasald** [SS13-SCP13/SS13-SCP13#329]
#### Description of issue
Once 173's cell is cleaned there doesn't seem to be any reason to open it ever again. Maybe if there was some kinda ability for it to spawn a 'mess', it would force of enable more reasons to go in there to clean. Cool down would be a few minutes I think? like 5 to 10?

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: 8e3288a692d078fd2d0a01f9e7d6da4e34ea985a - experimental - 2018-08-26
Game ID: bWq-dGgi
Current map: Foundation Site 53

**Comment by ghost** [comment]
It already does, every so often

**Comment by JakeDaBoss** [comment]
@steamp0rt not if 173 is player controlled.

**Comment by JakeDaBoss** [comment]
Already happens. But I am making a separate issue for this.
