### ISSUE TITLE
Something to help medical staff

### ISSUE THREAD

**Issue by El-Fishii** [SS13-SCP13/SS13-SCP13#332]
#### Description of issue

More than half of the issues are horrid blood loss, and even with roller beds they'll arrive to the physicians in a state of absolute death.  What I'm asking for is that Security guards, at least Cell and up, can carry and use Trauma kits to stop blood flow. You'd assume it'd be 'simple' and it keeps them from dying on the way to being dragged to medical. Even auto injector Painkillers. Those the medical staff get but they're meant for 'inexperienced staff' to be able to quickly use in an emergency. Could specialized Security have Medical bandages and painkillers to help with Triage of patients? Would really help with the deaths.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this]( https://github.com/SS13-SCP13/SS13-SCP13/issues )

**Comment by JakeDaBoss** [comment]
I mean, can't they just get it from one of the medical posts?

**Comment by El-Fishii** [comment]
They could. But are they? They probably consider it lowrp to take medical supplies and use it. When I get on I'll probably be making announcements to sec to do it anyways

**Comment by JakeDaBoss** [comment]
Fair enough, but this has been fixed. I added more traumakits.
