### ISSUE TITLE
Dream seeker has crashed.

### ISSUE THREAD

**Issue by Graffyz** [SS13-SCP13/SS13-SCP13#333]
Game crashes like hell for me,i don't know if i am the only one who has this problem but i'm really into SCP roleplaying and this is kinda frustrating.

#### Description of issue
    The game crashes after almost like 5 or 10 minutes,even if i stick as an observer and watch somebody for 5 or 10 minutes and i press click my whole thing freezes and it says that Dream seeker has crashed,i've never had this problem before and as i've said it's pretty frustrating

#### Length of time in which bug has been known to occur

	After 5 or 10 or 15 minutes in-round as observing,sometimes it happens while playing as well,which i can't explain to be honest.

#### Client version, Server revision & Game ID
Server Revision: 8e3288a692d078fd2d0a01f9e7d6da4e34ea985a - experimental - 2018-08-26
Game ID: bWr-aKf6.

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this]( https://github.com/SS13-SCP13/SS13-SCP13/issues )

**Comment by JakeDaBoss** [comment]
Please make sure you are running the latest beta, and running BYOND as admin. Then the crashes should be limited to two times at roundstart.

**Comment by Affurit** [comment]
I don't even get those first two times.
