### ISSUE TITLE
SCP-173 does not spawn mucus, gibs or blood if player-controlled.

### ISSUE THREAD

**Issue by JakeDaBoss** [SS13-SCP13/SS13-SCP13#337]
#### Description of issue
@Tasald got the right idea, but it does spawn it if AI controlled.

#### Difference between expected and actual behavior
Should spawn if player-controlled too.

#### Steps to reproduce 
Join as SCP-173.
Wait for nothing to happen.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this]( https://github.com/SS13-SCP13/SS13-SCP13/issues )

**Comment by Tasald** [comment]
oooh ok. and yea no real way to dirty the cell other then scuff the floor a tone. but that might be hard to see on the cams I think.

**Comment by kachnov** [comment]
fixed
