### ISSUE TITLE
The doors leading to Engineering do not have a wall between the double-doors

### ISSUE THREAD

**Issue by Ryboflave** [SS13-SCP13/SS13-SCP13#351]
#### Description of issue
The Engineering Doors, north of the Tram Blast Doors, do not have a wall between them. This renders the doors useless.

#### Difference between expected and actual behavior
Expected - A wall is present between the doors, forcing you to walk through the doors

Actual - There is no wall present between the doors, allowing you to bypass the doors

#### Steps to reproduce 
- Enter Engineering via the Tram
- Head north through the interlocking blast doors
- Head West at the bend on the hall
- Walk through the middle of the doors

#### Length of time in which bug has been known to occur

At least since September 19th, 2018

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: 24f92dd3313b909656010d8bf4d9dc7535ca3c7e - experimental - 2018-09-21

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this]( https://github.com/SS13-SCP13/SS13-SCP13/issues )

**Comment by Bxil** [comment]
I did run into this accidentally myself. In the editor it may seem that there is a wall because wall paint is applied, but there is a floor turf below instead.
