### ISSUE TITLE
Elevators can kill SCP-106

### ISSUE THREAD

**Issue by IcedPotato** [SS13-SCP13/SS13-SCP13#360]
#### Description of issue

Elevators can crush and kill SCP-106.

#### Difference between expected and actual behavior

Isn't he supposed to be borderline immortal?

#### Steps to reproduce 

Spawn as SCP-106, go to an elevator, call it, warp through the door, be gibbed.

#### Specific information for locating

Should work fine in HCZ elevators. Make sure the elevator is on the top level and you're on the bottom level.

#### Length of time in which bug has been known to occur

*shrug*

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: 8e3288a692d078fd2d0a01f9e7d6da4e34ea985a - experimental - 2018-08-26
Game ID: bWs-dcpQ
Current map: Foundation Site 53

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this]( https://github.com/SS13-SCP13/SS13-SCP13/issues )

**Comment by JakeDaBoss** [comment]
As it should. Not really an issue, since you can't prevent this.
