### ISSUE TITLE
A list of things borgs dont have access to and cant do

### ISSUE THREAD

**Issue by Cobraman202** [SS13-SCP13/SS13-SCP13#38]
Cant Access:
Elevator maintenance
Waste plant
Some APCs 
Some Air Alarms
Logistics Warehouse 
Logistics Officer
Checkpoint Alpha
Entrance sub stations 

Cant
Open file cabinet  
Enter cryo pods

**Comment by JakeDaBoss** [comment]
Borgs are meant to be removed anyway.
