### ISSUE TITLE
500 doesn't cure teh 049 pestilence.

### ISSUE THREAD

**Issue by Tasald** [SS13-SCP13/SS13-SCP13#381]
#### Description of issue
Took 500 during a code black, but was still converted into a 049-1 any way.

#### Difference between expected and actual behavior
I would have expected to not be able to be converted since 500 should remove any kinda 'disease/pestilence in a body.

#### Steps to reproduce 
Get 500 bottle
take 1 pill
get abused by 049 any way

#### Length of time in which bug has been known to occur

Just found it out today

#### Client version, Server revision & Game ID

Server revision compiled on: 
No commit information
Server tools version: 4.0.0.0

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this]( https://github.com/SS13-SCP13/SS13-SCP13/issues )

**Comment by Affurit** [comment]
I'll look into this. Thank you for reporting this to us.
