### ISSUE TITLE
Job Timelocking Balancing

### ISSUE THREAD

**Issue by JarlElbow** [SS13-SCP13/SS13-SCP13#383]
**Issue:**
One of the main issues I see with the server currently is people joining, picking a rather important/dangerous job, yet still having no idea what to do with them. Adding in the system that would lock away jobs for people who haven't been on the server long enough was a good first step, but I think it could be balanced just a bit more. Other servers such as baystation has this organized in a similar manner.

On the first day or two, one would join the server with only a couple of the basic civilian jobs. This would include Class-D, Chef, Bartender, Janitor, Archivist, and any other 'assistant' job with no important role. Any job with weapons would be strictly off limits at first. This gives players a chance to learn the map and how things are run.

On the third or fourth day, players would start to unlock jobs meant to train newer players in certain departments. Medical trainee, research trainee, security trainee, engineering, ect. Players would know the map at this point, and have a slightly easier time getting to know their new departments.

After about six to eight days, the regular jobs for each department would become available. Guards, EMTs, Researchers, Engineers. Players will know the server at this point, and can be trusted with higher priority roles.

After this, senior roles, and eventually administrative should be held out until the players are capable of being actual leaders in their departments. So, 10+ days.

**Comment by Pandolphina** [comment]
Couple points

First, Archivist should be time locked since it requires a LOT of lore knowledge, usually.

Second, 4 days to play a trainee role is kinda a terrible idea. Leave trainee roles unlocked.

**Comment by JarlElbow** [comment]
Well, Security trainee at the very least should be locked. I just don't trust day-1 players as that role, since they get the same gear as regular guards, and usually have no idea what they are doing.

**Comment by pronyacat** [comment]
Sorry for this *necro* answer but I as experienced medic don't want to wait 12 days to unlock Medical Doctor because I'm *new* to this server.
Or play as medical intern because of reasons.

**Comment by Pandolphina** [comment]
Yeah.

People keep complaining about "nobody plays medical" but it's a bit hard with a TIME LOCK.

Just lock all Senior and command roles and that's it.
