### ISSUE TITLE
Bus mainframe

### ISSUE THREAD

**Issue by NortonDK** [SS13-SCP13/SS13-SCP13#398]
#### Description of issue
The bus mainframes at telecoms goes offline after some time, potentially causing the telecoms issues

#### Difference between expected and actual behavior
Not turning off, unless power goes out

#### Steps to reproduce 
start the game and wait

#### Client version, Server revision & Game ID
Current version of today, with the new D block

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this]( https://github.com/SS13-SCP13/SS13-SCP13/issues )

**Comment by JakeDaBoss** [comment]
That's strange. Will look into.

**Comment by NortonDK** [comment]
It could be a heat issue inside the telecoms room. from what i've learned from discord discussions with Pandolphina
