### ISSUE TITLE
Lack of Anomaly Gear

### ISSUE THREAD

**Issue by Pandolphina** [SS13-SCP13/SS13-SCP13#399]
-->

#### Description of issue
The Anomaly Lab has no radiation suits, spectrometer, or anomaly suits.

Spectrometer needed to analyze artifacts, rad suits to protect from spectrometer rads, anomaly suits to prevent from anomalies.

#### Difference between expected and actual behavior
Stuff should be in the lab

It isn't.

#### Steps to reproduce 
Ghost
Fly over to the anomaly lab
Cry

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this]( https://github.com/SS13-SCP13/SS13-SCP13/issues )

**Comment by JakeDaBoss** [comment]
Rad suits no longer necessary due to us removing the radiating effect on anomalies. The rest is valid, though.
