### ISSUE TITLE
Corporal and Private spawn without ID Cards

### ISSUE THREAD

**Issue by JakeDaBoss** [SS13-SCP13/SS13-SCP13#4]
Reference: maps/ds90/job/jobs.dm and outfits.dm

For reference to the card ID's please go to maps/ds90/items/cards_ids.dm

Datums should be in order, unknown why this is fucking up. Spawns correctly for the Security Commander.

**Comment by PigeonLord** [comment]
Fixed.

**Comment by EndlessEllipse** [comment]
Resolved.
