### ISSUE TITLE
Rad suits to protect from spectrometer rad

### ISSUE THREAD

**Issue by Pandolphina** [SS13-SCP13/SS13-SCP13#403]
-->

#### Description of issue
Anomaly area needs rad suits because the mass spectrometer gives off radiation while scanning artifacts

#### Difference between expected and actual behaviors

We should have rad suits

We don't 

#### Steps to reproduce 
1. Join as scientist
2. Go to anomaly lab.  
3. Try to scan an artifact
4. Die of radiation

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this]( https://github.com/SS13-SCP13/SS13-SCP13/issues )

**Comment by JakeDaBoss** [comment]
In this case I'll add them.
