### ISSUE TITLE
Make Seperate Uniforms for Agent, Guard (and subsequently Cell Guard), and MTF

### ISSUE THREAD

**Issue by ComradeCorbyn** [SS13-SCP13/SS13-SCP13#430]
#### Description of issue
Perhaps make new sprites to distinct all the different Security branches from each other. Perhaps how Helmets work currently, with white lines on helmets indicating Zone Commander or higher, and blue lines indicating lower. Maybe something more distinct, but I don't know. Thanks!

**Comment by JakeDaBoss** [comment]
Also no. Confusion goes for D-Class that whoever they attack may have lasting consequences.
