### ISSUE TITLE
Shield walls randomly break/ self delete for no reason.

### ISSUE THREAD

**Issue by Tasald** [SS13-SCP13/SS13-SCP13#431]
#### Description of issue
The shield walls pictured here
https://gyazo.com/e5cfd655fc1e2a1bc06f420b0a06a6c0

Randomly deleted with no staff on, not sure if they are supposed to do this or what.

#### Difference between expected and actual behavior
Expected the wall to stay solid and not have large gaps in it that make no since when the rest is still up.

#### Steps to reproduce 
Set up 106's shields
Wait for the mto break.
Suprise code red and die.

#### Length of time in which bug has been known to occur
Two rounds at least.

#### Client version, Server revision & Game ID

Server revision compiled on: 2018-08-26
Master commit: 1bdfa7de98aaecc57d5c5ad42d066104ada3241a 
Local commit: 8e3288a692d078fd2d0a01f9e7d6da4e34ea985a

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this]( https://github.com/SS13-SCP13/SS13-SCP13/issues )

**Comment by JakeDaBoss** [comment]
Someone shot the shield wall. Disable and re-enable. If this is still an issue, please open another issue with the particular issue.
