### ISSUE TITLE
Missing Wiring in SMES room, breaks power for Facility

### ISSUE THREAD

**Issue by Crystal9156** [SS13-SCP13/SS13-SCP13#459]
#### Description of issue

Power Oversight in SMES room

#### Difference between expected and actual behavior
There's no wire when there should be

#### Steps to reproduce 
Walk into SMES room. 
Look at wiring leading into wall.
Learn that Wiring doesn't go UNDER the wall.
Deconstruct wall and put wiring.
Fix Power.
Profit.

#### Specific information for locating

http://prntscr.com/l10hc1

#### Length of time in which bug has been known to occur

Probably a while

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X ] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this]( https://github.com/SS13-SCP13/SS13-SCP13/issues )

**Comment by JakeDaBoss** [comment]
Do you have coords for me?

**Comment by Crystal9156** [comment]
I posted a picture

**Comment by Crystal9156** [comment]
There's normally a wall there and no wiring underneath. The coords are 59, 50, 2

**Comment by Goodfishie** [comment]
I don't think it necessarily needs another issue to be raised but in addition to wiring oddities, there are two power cables under the SMES in the fusion room, and no power terminal

Seems to work without it though somewhat
