### ISSUE TITLE
No bio-printers in medbay.

### ISSUE THREAD

**Issue by pronyacat** [SS13-SCP13/SS13-SCP13#461]
#### Description of issue
Getting a necrotic organ means that this person can go straight to the morgue.
Doctors can't save people.

#### Difference between expected and actual behavior
Was expected bioprinters in the surgery room. 

#### Steps to reproduce 
There just no bio-printers.

#### Specific information for locating
Medical bay.

#### Length of time in which bug has been known to occur
02.10.2018 - found that no bio-printers on the map

#### Client version, Server revision & Game ID
Master commit: 1bdfa7de98aaecc57d5c5ad42d066104ada3241a 
Local commit: 8e3288a692d078fd2d0a01f9e7d6da4e34ea985a

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this]

**Comment by Goodfishie** [comment]
theoretically you can just use a D-Class as a doner, but I think they have to be a compatible blood type.


I try to keep my eyes on crew records for O- D-Class so I know whose kidneys I'm taking

but if this isn't how it's meant to be then I think this is a good idea

**Comment by JakeDaBoss** [comment]
This will remain open until fixed in +- 2 weeks.
