### ISSUE TITLE
Please fix the cameras for SCP-012

### ISSUE THREAD

**Issue by El-Fishii** [SS13-SCP13/SS13-SCP13#484]
#### Description of issue

Okay, maybe I'm dumb, as it did say WARNING. but still. Low level scientists have access to the 012 camera. So being able to see Keter SCP-895, which it defaults to. Is... Disturbing to say the least.

#### Difference between expected and actual behavior

I'd feel we would have an entirely different camera network to the Heavy Containment and Low Containment. Not to mention aren't we not supposed to see 895 through cameras? Isn't that what causes the insanity?

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this]( https://github.com/SS13-SCP13/SS13-SCP13/issues )

**Comment by JakeDaBoss** [comment]
SCP-895 having camera's is lore appropriate. That said, I'll look into the issue.

**Comment by JakeDaBoss** [comment]
Fixed.
