### ISSUE TITLE
Ghosts can use the RUST Console

### ISSUE THREAD

**Issue by Pandolphina** [SS13-SCP13/SS13-SCP13#486]
#### Description of issue
Title

#### Difference between expected and actual behavior
Ghosts shouldn't be able to use the console

They can

#### Steps to reproduce 
1. Be ghost
2. Go to RUST
3. HAHA FIELD 2000

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this]( https://github.com/SS13-SCP13/SS13-SCP13/issues )

**Comment by lolmemelord123** [comment]
stealer
u stole my bug report :-1:

**Comment by JakeDaBoss** [comment]
Unless regular ghosts can interact with it, this is because you're a Moderator.

**Comment by lolmemelord123** [comment]
i did it and it works like 2+ times

**Comment by Pandolphina** [comment]
Wasn't me who did it. Was a bunch of player ghosts.

**Comment by lolmemelord123** [comment]
it was david blanc
thats me
