### ISSUE TITLE
Access issues in medical.

### ISSUE THREAD

**Issue by pronyacat** [SS13-SCP13/SS13-SCP13#498]
#### Description of issue
medical doctor doesn't have access to medical equipment closets

#### Difference between expected and actual behavior

They should have.

#### Steps to reproduce 

Join MD, try to open med equip closets

#### Specific information for locating
AFAIK, all med equip closets

#### Length of time in which bug has been known to occur
12.10.2018

#### Client version, Server revision & Game ID
Server revision compiled on: 2018-08-26
Master commit: 1bdfa7de98aaecc57d5c5ad42d066104ada3241a 
Local commit: 8e3288a692d078fd2d0a01f9e7d6da4e34ea985a

#### Issue bingo

- [ x] Issue could be reproduced at least once
- [ x] Issue could be reproduced by different players
- [ x] Issue could be reproduced in multiple rounds
- [x ] Issue happened in a recent (less than 7 days ago) round
- [x ] [Couldn't find an existing issue about this]( https://github.com/SS13-SCP13/SS13-SCP13/issues )

**Comment by pronyacat** [comment]
Also I found out that MD doesn't even have access to suit sensors programm.

**Comment by pronyacat** [comment]
Welp, now medics don't have access even to LCZ tram, HCZ, administration office and other.

**Comment by JakeDaBoss** [comment]
Leftover stuff from the refactor. My bad. Will be addressed ASAP.

**Comment by JakeDaBoss** [comment]
The access being unable to access the LCZ is intended. Far too often did doctors stray from the Medical Bay to the D-Class Post, rendering anyone with EMT job to be useless. If you want to work D-Class, then join as EMT, not as Doctor.

**Comment by pronyacat** [comment]
Ahh..Well, when I only one MD and everybody yell MD to here...
That seems now its not my problem
