### ISSUE TITLE
Security Guard Gear Issues

### ISSUE THREAD

**Issue by Pandolphina** [SS13-SCP13/SS13-SCP13#499]
#### Description of issue
Couple things. First, pistols should be .45s. Second, all the guards have identical gear. I believe we planned to remove things like SMGs from EZ guards and give them less bulky gear. 

#### Difference between expected and actual behavior
9MMs should be replaced with .45s, EZ guards should not have SMGs and should get some cool suit or something.

#### Steps to reproduce 
1. Join as EZ guard
2. Go to locker
3. Cry

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this]( https://github.com/SS13-SCP13/SS13-SCP13/issues )

**Comment by JakeDaBoss** [comment]
EZ Guards will always have SMG's. What are you talking about. The other issue is being fixed, though.
