### ISSUE TITLE
People still have a pulse after getting killed by SCP-173.

### ISSUE THREAD

**Issue by IcedPotato** [SS13-SCP13/SS13-SCP13#500]
#### Description of issue

People still have a pulse after getting killed by SCP-173.

#### Difference between expected and actual behavior

They shouldn't.

#### Steps to reproduce 

Get killed by 173.

#### Client version, Server revision & Game ID

Server revision compiled on: 2018-08-26
Master commit: 1bdfa7de98aaecc57d5c5ad42d066104ada3241a 
Local commit: 8e3288a692d078fd2d0a01f9e7d6da4e34ea985a

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [] Issue could be reproduced by different players
- [] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this]( https://github.com/SS13-SCP13/SS13-SCP13/issues )

**Comment by pronyacat** [comment]
We have brainmed here. SCP-173 Just kill you, not the brain. That's because you have a pulse.

**Comment by JakeDaBoss** [comment]
The brain is actually killed.

**Comment by pronyacat** [comment]
> 
> 
> The brain is actually killed.

Yep, patient is braindead but we expect that brain would have at least any damage.
Like oxydamage, toxin damage, brute damage. Medical scanner says that brain activity at 0% but the brain itself has NO damage at all.
Sorry for that necropost, Lion.

**Comment by JakeDaBoss** [comment]
No prob, @pronyacat.

If we look at the brain, it has 200 damage post-173 snap. So that debunks that.
