### ISSUE TITLE
This is not how you fix merge conflicts.

### ISSUE THREAD

**Issue by Iamgoofball** [SS13-SCP13/SS13-SCP13#519]
https://github.com/SS13-SCP13/SS13-SCP13/commit/21d070b29c0f275e9530d23c0eb5b092da1953a4#diff-269e9307ef6ce8a774956be1d2d9ec97R86

Did you test your compile? Make sure to run a compile before committing after fixing a merge conflict. I recommend getting TortoiseGIT to make it easy.

**Comment by JakeDaBoss** [comment]
It looks like it was fixed. On my most recent branch it compiles, which has this commit, since I removed it in 7170677f099c4c0c9417ade0708158e3023e5622
