### ISSUE TITLE
SCP13 is an AGPL codebase. Please read your licensing terms you agreed to when you created your fork of baystation code before you continue harassing legitimate AGPL downstreams.

### ISSUE THREAD

**Issue by Iamgoofball** [SS13-SCP13/SS13-SCP13#532]
Please see the title.

You are an AGPL codebase. Please read your licensing terms you agreed to that are present in your repository as of 4:27 PM PST 10/18/2018 when you created your fork of baystation code before you continue harassing legitimate AGPL downstreams.

This is unacceptable behavior and will not be tolerated. Continued abuse of legal threats will result in the Free Software Foundation being informed.

Additionally, I do hope your patrons do reconsider relocating their funds to servers and owners that do not directly harass and deride

**Comment by ghost** [comment]
Original post archived, just incase you-know-who removes/edits it:

https://web.archive.org/web/20181018233022/https://github.com/SS13-SCP13/SS13-SCP13/issues/532
https://archive.is/Pc8Eb

**Comment by Iamgoofball** [comment]
cut the name down, was too long and irrelevant to the copyright issue

**Comment by JakeDaBoss** [comment]
Please stop posting irrelevant information based on dated evidence. Else I'll have to give punishment.

**Comment by Iamgoofball** [comment]
Your licensing terms that you agreed to when you forked are not irrelevant, but sure.

**Comment by JakeDaBoss** [comment]
They are irrelevant to this situation.
