### ISSUE TITLE
Cargonia layout is annoying.

### ISSUE THREAD

**Issue by IcedPotato** [SS13-SCP13/SS13-SCP13#543]
#### Description of issue

Please make it so players don't have to go all the way around this area to use the belt and move crates.

https://i.imgur.com/XmNs6Bw.png

**Comment by JakeDaBoss** [comment]
That's why you have two. One goes for export and import from the shuttle. Second one goes for distribution and packaging. QM goes where necessary. I might increase LS positions to 3 though.
