### ISSUE TITLE
Holding Creatures bug

### ISSUE THREAD

**Issue by TheBucketBip** [SS13-SCP13/SS13-SCP13#556]
A player reported a bug when holding a Neaera which is just a monkey with a different look. I assume he got it via cargo but the creature itself doesn't make much sense for being in our server. It causes this to happen when being held, which you can see in the image below.

![](https://i.gyazo.com/5f6cda5d585cd1042b19c2449c926a6b.png)

**Comment by Autismobirb** [comment]
It's the lack of a icon state for being in your hand, easy fix lemme bash something up and I'll throw it to Rhi tomorrow

**Comment by Autismobirb** [comment]
It's the lack of a icon state for being in your hand, easy fix lemme bash something up and I'll throw it to Rhi tomorrow
