### ISSUE TITLE
Command roles still get traitor

### ISSUE THREAD

**Issue by Bryssel** [SS13-SCP13/SS13-SCP13#578]
#### Description of issue

Command roles still get traitor

#### Difference between expected and actual behavior

It's quite obvious that if you're in the command positions inside a site facility, you couldn't possibly be a GOI operative

#### Steps to reproduce 

Get lucky

#### Specific information for locating

Command roles

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this]( https://github.com/SS13-SCP13/SS13-SCP13/issues )

**Comment by TheSleepyCatmom** [comment]
Not the issue with Command Roles, it's the issue with the Chief Engineer specifically. Also, 95% sure we don't have antag-lock enabled at the current time.

**Comment by JakeDaBoss** [comment]
Issue located and remedied.
