### ISSUE TITLE
Generalized Problems

### ISSUE THREAD

**Issue by TheSleepyCatmom** [SS13-SCP13/SS13-SCP13#579]
#### Description of issue
Guard Commander uniform spawns on the Chief engineer, and not the Guard commander
Chief Engineer is labeled in Misc., and not in Engineering or Command

#### Difference between expected and actual behavior
Chief Engineer is the Chief Engineer Command Role. Not a Misc role.
Chief Engineer should spawn with an Engineering suit, and not a Guard Commander suit.
Guard Commander should spawn with their uniform.

#### Steps to reproduce 
Spawn as Chief Engineer

#### Length of time in which bug has been known to occur

Several weeks. Reported already, was forgotten about so it goes here.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this]( https://github.com/SS13-SCP13/SS13-SCP13/issues )

**Comment by JakeDaBoss** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Restore SCP13 stability](https://trello.com/c/fohv7Pc8/11-restore-scp13-stability)
