### ISSUE TITLE
Site Director doesn't have full camera control

### ISSUE THREAD

**Issue by Daman453** [SS13-SCP13/SS13-SCP13#587]
#### Description of issue

As Site Director, you do not have full access to cam control. Makes it hard to see if your zone commander is joking when he says 049 has breached containment

#### Difference between expected and actual behavior
Want to check cameras. Only access to EZ and Engineering.

#### Steps to reproduce 
Spawn in as Site Director.
Get bad ZC
Go to code red because you can't see 049 containtment.

#### Length of time in which bug has been known to occur

Not sure
#### Client version, Server revision & Game ID

current
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this]( https://github.com/SS13-SCP13/SS13-SCP13/issues )

**Comment by JakeDaBoss** [comment]
This is intended, since camera's might contain memetic hazards, which Class A's are meant to be shielded from.

**Comment by Daman453** [comment]
Gameplay > Lore Right now the gameplay is hiding inside of a office until things get fucked.
