### ISSUE TITLE
SCP-106 will remain stuck in the PD if he is recontained while he's in the PD.

### ISSUE THREAD

**Issue by JakeDaBoss** [SS13-SCP13/SS13-SCP13#593]
#### Description of issue
Upon activation of the femur breaker, while SCP-106 is in his pocket dimension, will render him unable to return to the station. The return / enter pocket dimension will keep SCP-106 in the pocket dimension.

#### Difference between expected and actual behavior
Should be returned to the station if he is in the pocket dimension if the FB is activated.

#### Steps to reproduce 
SCP-106 in PD
Activate Femur Breaker
Return to SCP-106
Try the commands listed.

**Comment by kachnov** [comment]
fixed in #599
