### ISSUE TITLE
Devsay simply does not work

### ISSUE THREAD

**Issue by Affurit** [SS13-SCP13/SS13-SCP13#73]
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

Devsay doth not work. This is so sad.

**Comment by JakeDaBoss** [comment]
Should work now.
