### ISSUE TITLE
SCP-106 gets pain locked.

### ISSUE THREAD

**Issue by Wulfestwulf** [SS13-SCP13/SS13-SCP13#89]
#### Description of issue
SCP-106 gets pain locked.

#### Difference between expected and actual behavior
Shouldn't be able to get pain locked as a 106 who cant even feel pain.

#### Steps to reproduce 
Be 106, get shot to shit, cant do anything.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by JakeDaBoss** [comment]
Issue should be fixed.
